//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheRentersPlace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appartment()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int AppartmentId { get; set; }
        public int ManagerId { get; set; }
        public string CivicAddress { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public decimal NoOfBedrooms { get; set; }
        public string Type { get; set; }
        public decimal Price { get; set; }
        public string Status { get; set; }
        public string PictureURL { get; set; }
    
        public virtual Manager Manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
