//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheRentersPlace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppartmentId { get; set; }
        public int TenantId { get; set; }
        public int ManagerId { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public string Purpose { get; set; }
        public string Note { get; set; }
    
        public virtual Appartment Appartment { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
